baseURL = "https://homilae.github.io/"
locale = "en-us"
title = "Homiliae"
# theme = "PaperMod"
[pagination]
  pagerSize = 5

[params]
  description = "An open-access archive of Catholic homilies and sermons, with original language texts and English translations."
  defaultTheme = "light"
  ShowReadingTime = false
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = false


[taxonomies]
  author = "authors"
  period = "periods"
  language = "languages"
  tag = "tags"
  liturgical_occasion = "liturgical_occasions"
  audience = "audiences"
  theme = "themes"
  homily_type = "homily_types"
  verse = "verses"

[outputs]
  home = ["HTML", "JSON"]
  page = ["HTML"]
  section = ["HTML"]
  taxonomy = ["HTML"]
  term = ["HTML"]


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true